package treenipaivakirja.test;
// Generated by ComTest BEGIN
import java.io.File;
import treenipaivakirja.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:26:57 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LajitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta40 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta40() throws SailoException {    // Lajit: 40
    Lajit lajit = new Lajit(); 
    Laji laji1 = new Laji(), laji2 = new Laji(); 
    laji1.taytaLajinTiedot(); 
    laji2.taytaLajinTiedot(); 
    String hakemisto = "treenipaivakirja_tiedostot_testit"; 
    String tiedNimi = hakemisto+"/treenittesti"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    lajit.lueTiedostosta(tiedNimi); 
    fail("Lajit: 54 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    lajit.lisaa(laji1); 
    lajit.lisaa(laji2); 
    lajit.tallenna(); 
    lajit = new Lajit();  // Poistetaan vanhat luomalla uusi
    lajit.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    lajit.lisaa(laji2); 
    lajit.tallenna(); 
    assertEquals("From: Lajit line: 62", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Lajit line: 64", true, fbak.delete()); 
    assertEquals("From: Lajit line: 65", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator184 */
  @Test
  public void testIterator184() {    // Lajit: 184
    Lajit lajeja = new Lajit(); 
    Laji laji1 = new Laji(); laji1.rekisteroi(); lajeja.lisaa(laji1); 
    Laji laji2 = new Laji(); laji2.rekisteroi(); lajeja.lisaa(laji2); 
    Laji laji3 = new Laji(); laji3.rekisteroi(); lajeja.lisaa(laji3); 
    Laji laji4 = new Laji(); laji4.rekisteroi(); lajeja.lisaa(laji4); 
    Laji laji5 = new Laji(); laji5.rekisteroi(); lajeja.lisaa(laji5); 
    Laji laji6 = new Laji(); 
    Iterator<Laji> i2 = lajeja.iterator(); 
    assertEquals("From: Lajit line: 197", laji1, i2.next()); 
    assertEquals("From: Lajit line: 198", laji2, i2.next()); 
    assertEquals("From: Lajit line: 199", laji3, i2.next()); 
    assertEquals("From: Lajit line: 200", laji4, i2.next()); 
    assertEquals("From: Lajit line: 201", laji5, i2.next()); 
    try {
    assertEquals("From: Lajit line: 202", laji6, i2.next()); 
    fail("Lajit: 202 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int ljid[] = { 1,2,3,4,5} ; 
    for (Laji laj : lajeja) {
    assertEquals("From: Lajit line: 208", ljid[n], laj.getId()); n++; 
    }
    assertEquals("From: Lajit line: 211", 5, n); 
  } // Generated by ComTest END
}