package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:26:32 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class LajiTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi56 */
  @Test
  public void testRekisteroi56() {    // Laji: 56
    Laji laji1 = new Laji(); 
    assertEquals("From: Laji line: 58", 0, laji1.getId()); 
    laji1.rekisteroi(); 
    Laji laji2 = new Laji(); 
    laji2.rekisteroi(); 
    int idNumero1 = laji1.getId(); 
    int idNumero2 = laji2.getId(); 
    idNumero1 = idNumero2 - 1; 
    laji1.rekisteroi(); 
    assertEquals("From: Laji line: 66", idNumero1, laji1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse128 */
  @Test
  public void testParse128() {    // Laji: 128
    Laji laji = new Laji(); 
    laji.parse(" 3 |  jooga  | 0 | 0 "); 
    assertEquals("From: Laji line: 131", 3, laji.getId()); 
    assertEquals("From: Laji line: 132", true, laji.toString().startsWith("3|jooga|0|0")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString168 */
  @Test
  public void testToString168() {    // Laji: 168
    Laji laji = new Laji(); 
    laji.parse("   3  | jooga | 0 | 4"); 
    assertEquals("From: Laji line: 171", true, laji.toString().startsWith("3|jooga|0|4"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
  } // Generated by ComTest END
}