package treenipaivakirja.test;
// Generated by ComTest BEGIN
import java.io.File;
import treenipaivakirja.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:27:20 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenipaikatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta83 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta83() throws SailoException {    // Treenipaikat: 83
    Treenipaikat treenipaikat = new Treenipaikat(); 
    Treenipaikka treenipaikka1 = new Treenipaikka(), treenipaikka2 = new Treenipaikka(); 
    treenipaikka1.taytaTreenipaikanTiedot(); 
    treenipaikka2.taytaTreenipaikanTiedot(); 
    String hakemisto = "treenipaivakirja_tiedostot_testit"; 
    String tiedNimi = hakemisto+"/treenittesti"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    treenipaikat.lueTiedostosta(tiedNimi); 
    fail("Treenipaikat: 97 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    treenipaikat.lisaa(treenipaikka1); 
    treenipaikat.lisaa(treenipaikka2); 
    treenipaikat.tallenna(); 
    treenipaikat = new Treenipaikat();  // Poistetaan vanhat luomalla uusi
    treenipaikat.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    treenipaikat.lisaa(treenipaikka2); 
    treenipaikat.tallenna(); 
    assertEquals("From: Treenipaikat line: 105", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Treenipaikat line: 107", true, fbak.delete()); 
    assertEquals("From: Treenipaikat line: 108", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator214 */
  @Test
  public void testIterator214() {    // Treenipaikat: 214
    Treenipaikat treenipaikkoja = new Treenipaikat(); 
    Treenipaikka treenipaikka1 = new Treenipaikka(); treenipaikka1.rekisteroi(); treenipaikkoja.lisaa(treenipaikka1); 
    Treenipaikka treenipaikka2 = new Treenipaikka(); treenipaikka2.rekisteroi(); treenipaikkoja.lisaa(treenipaikka2); 
    Treenipaikka treenipaikka3 = new Treenipaikka(); treenipaikka3.rekisteroi(); treenipaikkoja.lisaa(treenipaikka3); 
    Treenipaikka treenipaikka4 = new Treenipaikka(); treenipaikka4.rekisteroi(); treenipaikkoja.lisaa(treenipaikka4); 
    Treenipaikka treenipaikka5 = new Treenipaikka(); treenipaikka5.rekisteroi(); treenipaikkoja.lisaa(treenipaikka5); 
    Treenipaikka treenipaikka6 = new Treenipaikka(); 
    Iterator<Treenipaikka> i2 = treenipaikkoja.iterator(); 
    assertEquals("From: Treenipaikat line: 227", treenipaikka1, i2.next()); 
    assertEquals("From: Treenipaikat line: 228", treenipaikka2, i2.next()); 
    assertEquals("From: Treenipaikat line: 229", treenipaikka3, i2.next()); 
    assertEquals("From: Treenipaikat line: 230", treenipaikka4, i2.next()); 
    assertEquals("From: Treenipaikat line: 231", treenipaikka5, i2.next()); 
    try {
    assertEquals("From: Treenipaikat line: 232", treenipaikka6, i2.next()); 
    fail("Treenipaikat: 232 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int tjid[] = { 1,2,3,4,5} ; 
    for (Treenipaikka treenip : treenipaikkoja) {
    assertEquals("From: Treenipaikat line: 238", tjid[n], treenip.getId()); n++; 
    }
    assertEquals("From: Treenipaikat line: 241", 5, n); 
  } // Generated by ComTest END
}