package treenipaivakirja.test;
// Generated by ComTest BEGIN
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:27:46 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta72 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta72() throws SailoException {    // Treenit: 72
    Treenit treenit = new Treenit(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    treeni1.taytaTreeninTiedot(); 
    treeni2.taytaTreeninTiedot(); 
    String hakemisto = "treenipaivakirja_tiedostot_testit"; 
    String tiedNimi = hakemisto+"/treenittesti"; 
    File ftied = new File(tiedNimi+".dat"); 
    File dir = new File(hakemisto); 
    dir.mkdir(); 
    ftied.delete(); 
    try {
    treenit.lueTiedostosta(tiedNimi); 
    fail("Treenit: 86 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    treenit.lisaa(treeni1); 
    treenit.lisaa(treeni2); 
    treenit.tallenna(); 
    treenit = new Treenit();  // Poistetaan vanhat luomalla uusi
    treenit.lueTiedostosta(tiedNimi);  // johon ladataan tiedot tiedostosta.
    treenit.lisaa(treeni2); 
    treenit.tallenna(); 
    assertEquals("From: Treenit line: 94", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Treenit line: 96", true, fbak.delete()); 
    assertEquals("From: Treenit line: 97", true, dir.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKasvataTaulukkoa200 */
  @Test
  public void testKasvataTaulukkoa200() {    // Treenit: 200
    Treenit treeneja = new Treenit(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(), treeni3 = new Treeni(),
    treeni4 = new Treeni(), treeni5 = new Treeni(), treeni6 = new Treeni(); 
    treeneja.lisaa(treeni1); assertEquals("From: Treenit line: 204", 1, treeneja.getLkm()); 
    treeneja.lisaa(treeni2); assertEquals("From: Treenit line: 205", 2, treeneja.getLkm()); 
    treeneja.lisaa(treeni3); assertEquals("From: Treenit line: 206", 3, treeneja.getLkm()); 
    treeneja.lisaa(treeni4); assertEquals("From: Treenit line: 207", 4, treeneja.getLkm()); 
    treeneja.lisaa(treeni5); assertEquals("From: Treenit line: 208", 5, treeneja.getLkm()); 
    treeneja.lisaa(treeni6); assertEquals("From: Treenit line: 209", 6, treeneja.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa225 */
  @Test
  public void testLisaa225() {    // Treenit: 225
    Treenit treeneja = new Treenit(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    treeneja.lisaa(treeni1); assertEquals("From: Treenit line: 228", 1, treeneja.getLkm()); 
    treeneja.lisaa(treeni2); assertEquals("From: Treenit line: 229", 2, treeneja.getLkm()); 
    assertEquals("From: Treenit line: 230", treeni1, treeneja.anna(0)); 
    assertEquals("From: Treenit line: 231", treeni2, treeneja.anna(1)); 
    treeneja.lisaa(treeni2); assertEquals("From: Treenit line: 232", 2, treeneja.getLkm()); 
    assertEquals("From: Treenit line: 233", false, treeneja.anna(1) == treeni1); 
    assertEquals("From: Treenit line: 234", true, treeneja.anna(0) == treeni1); 
    Treeni treeni3 = new Treeni(), treeni4 = new Treeni(), treeni5 = new Treeni(), treeni6 = new Treeni(); 
    treeneja.lisaa(treeni3); assertEquals("From: Treenit line: 236", 3, treeneja.getLkm()); 
    treeneja.lisaa(treeni4); assertEquals("From: Treenit line: 237", 4, treeneja.getLkm()); 
    treeneja.lisaa(treeni5); assertEquals("From: Treenit line: 238", 5, treeneja.getLkm()); 
    treeneja.lisaa(treeni6); assertEquals("From: Treenit line: 239", 6, treeneja.getLkm()); 
    assertEquals("From: Treenit line: 240", false, treeni1 == treeni2); 
    assertEquals("From: Treenit line: 241", false, treeni3 == treeni4); 
    assertEquals("From: Treenit line: 242", false, treeni1 == treeni6); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista261 
   * @throws SailoException when error
   */
  @Test
  public void testPoista261() throws SailoException {    // Treenit: 261
    Treenit treenit = new Treenit(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(), treeni3 = new Treeni(); 
    treeni1.rekisteroi(); treeni2.rekisteroi(); treeni3.rekisteroi(); 
    int id1 = treeni1.getId(); 
    treenit.lisaa(treeni1); treenit.lisaa(treeni2); treenit.lisaa(treeni3); 
    assertEquals("From: Treenit line: 268", 1, treenit.poista(id1+1)); 
    assertEquals("From: Treenit line: 269", 2, treenit.getLkm()); 
    assertEquals("From: Treenit line: 270", 1, treenit.poista(id1)); assertEquals("From: Treenit line: 270", 1, treenit.getLkm()); 
    assertEquals("From: Treenit line: 271", 0, treenit.poista(id1+3)); assertEquals("From: Treenit line: 271", 1, treenit.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnna312 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testAnna312() throws IndexOutOfBoundsException {    // Treenit: 312
    Treenit treeneja = new Treenit(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    treeneja.lisaa(treeni1); 
    treeneja.lisaa(treeni2); 
    assertEquals("From: Treenit line: 318", treeni1, treeneja.anna(0)); 
    assertEquals("From: Treenit line: 319", treeni2, treeneja.anna(1)); 
    try {
    treeneja.anna(-22); 
    fail("Treenit: 320 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm335 */
  @Test
  public void testGetLkm335() {    // Treenit: 335
    Treenit treeneja = new Treenit(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    assertEquals("From: Treenit line: 338", 0, treeneja.getLkm()); 
    treeneja.lisaa(treeni1); assertEquals("From: Treenit line: 339", 1, treeneja.getLkm()); 
    treeneja.lisaa(treeni2); assertEquals("From: Treenit line: 340", 2, treeneja.getLkm()); 
    treeneja.lisaa(treeni1); assertEquals("From: Treenit line: 341", 2, treeneja.getLkm()); 
  } // Generated by ComTest END
}