package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:27:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenipaikkaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi33 */
  @Test
  public void testRekisteroi33() {    // Treenipaikka: 33
    Treenipaikka treenipaikka1 = new Treenipaikka(); 
    assertEquals("From: Treenipaikka line: 35", 0, treenipaikka1.getId()); 
    treenipaikka1.rekisteroi(); 
    Treenipaikka treenipaikka2 = new Treenipaikka(); 
    treenipaikka2.rekisteroi(); 
    int idNumero1 = treenipaikka1.getId(); 
    int idNumero2 = treenipaikka2.getId(); 
    idNumero1 = idNumero2 - 1; 
    treenipaikka1.rekisteroi(); 
    assertEquals("From: Treenipaikka line: 43", idNumero1, treenipaikka1.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse99 */
  @Test
  public void testParse99() {    // Treenipaikka: 99
    Treenipaikka treenipaikka = new Treenipaikka(); 
    treenipaikka.parse("   3  |  Laajavuori "); 
    assertEquals("From: Treenipaikka line: 102", 3, treenipaikka.getId()); 
    assertEquals("From: Treenipaikka line: 103", true, treenipaikka.toString().startsWith("3|Laajavuori")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString137 */
  @Test
  public void testToString137() {    // Treenipaikka: 137
    Treenipaikka treenipaikka = new Treenipaikka(); 
    treenipaikka.parse("   3  | Honkalan kuntosali"); 
    assertEquals("From: Treenipaikka line: 140", true, treenipaikka.toString().startsWith("3|Honkalan kuntosali"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
  } // Generated by ComTest END
}