package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:27:13 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreeniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi48 */
  @Test
  public void testRekisteroi48() {    // Treeni: 48
    Treeni futista = new Treeni(); 
    assertEquals("From: Treeni line: 50", 0, futista.getId()); 
    futista.rekisteroi(); 
    Treeni futista1 = new Treeni(); 
    futista1.rekisteroi(); 
    int idNumero = futista.getId(); 
    int idNumero1 = futista1.getId(); 
    assertEquals("From: Treeni line: 56", idNumero1 - 1, idNumero); 
    futista.rekisteroi(); 
    assertEquals("From: Treeni line: 58", idNumero + 2, futista.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse142 */
  @Test
  public void testParse142() {    // Treeni: 142
    Treeni treeni = new Treeni(); 
    treeni.parse("   3  |  03.02.2018   | 3 | 120 | 4 | Liukupotku s‰‰rille!  "); 
    assertEquals("From: Treeni line: 145", 3, treeni.getId()); 
    assertEquals("From: Treeni line: 146", true, treeni.toString().startsWith("3|03.02.2018|3|"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
    treeni.rekisteroi(); 
    int n = treeni.getId(); 
    treeni.parse(""+(n+20));  // Otetaan merkkijonosta vain idnumero
    treeni.rekisteroi();  // ja tarkistetaan ett‰ seuraavalla kertaa tulee yht‰ isompi
    assertEquals("From: Treeni line: 152", n+20+1, treeni.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompareTo171 */
  @Test
  public void testCompareTo171() {    // Treeni: 171
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(), treeni3 = new Treeni(); 
    treeni1.parse("   3  |  03.02.2018   | 3 | 120 | 4 | Liukupotku s‰‰rille!  "); 
    treeni2.parse("   3  |  01.03.2012   | 3 | 120 | 4 | Liukupotku s‰‰rille!  "); 
    treeni3.parse("   3  |  03.02.2018   | 3 | 120 | 4 | Liukupotku s‰‰rille!  "); 
    assertEquals("From: Treeni line: 176", -1, treeni1.compareTo(treeni2)); 
    assertEquals("From: Treeni line: 177", 1, treeni2.compareTo(treeni1)); 
    assertEquals("From: Treeni line: 178", 0, treeni1.compareTo(treeni3)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString267 */
  @Test
  public void testToString267() {    // Treeni: 267
    Treeni treeni = new Treeni(); 
    treeni.parse("   3  |  03.02.2018   | 3 | 120 | 4 | Liukupotku s‰‰rille!  "); 
    assertEquals("From: Treeni line: 270", true, treeni.toString().startsWith("3|03.02.2018|3|"));  // on enemm‰kin kuin 3 kentt‰‰, siksi loppu |
  } // Generated by ComTest END
}