package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2018.05.04 08:27:41 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenipaivakirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testAnna46 
   * @throws IndexOutOfBoundsException when error
   */
  @Test
  public void testAnna46() throws IndexOutOfBoundsException {    // Treenipaivakirja: 46
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    treenipaivakirja.lisaa(treeni1); 
    treenipaivakirja.lisaa(treeni2); 
    assertEquals("From: Treenipaivakirja line: 52", treeni1, treenipaivakirja.anna(0)); 
    assertEquals("From: Treenipaivakirja line: 53", treeni2, treenipaivakirja.anna(1)); 
    try {
    treenipaivakirja.anna(-22); 
    fail("Treenipaivakirja: 54 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetLkm103 */
  @Test
  public void testGetLkm103() {    // Treenipaivakirja: 103
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    assertEquals("From: Treenipaivakirja line: 106", 0, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni1); assertEquals("From: Treenipaivakirja line: 107", 1, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni2); assertEquals("From: Treenipaivakirja line: 108", 2, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni1); assertEquals("From: Treenipaivakirja line: 109", 2, treenipaivakirja.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testLisaa119 */
  @Test
  public void testLisaa119() {    // Treenipaivakirja: 119
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Treeni treeni1 = new Treeni(), treeni2 = new Treeni(); 
    treenipaivakirja.lisaa(treeni1); assertEquals("From: Treenipaivakirja line: 122", 1, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni2); assertEquals("From: Treenipaivakirja line: 123", 2, treenipaivakirja.getLkm()); 
    assertEquals("From: Treenipaivakirja line: 124", treeni1, treenipaivakirja.anna(0)); 
    assertEquals("From: Treenipaivakirja line: 125", treeni2, treenipaivakirja.anna(1)); 
    treenipaivakirja.lisaa(treeni2); assertEquals("From: Treenipaivakirja line: 126", 2, treenipaivakirja.getLkm()); 
    assertEquals("From: Treenipaivakirja line: 127", false, treenipaivakirja.anna(1) == treeni1); 
    assertEquals("From: Treenipaivakirja line: 128", true, treenipaivakirja.anna(0) == treeni1); 
    Treeni treeni3 = new Treeni(), treeni4 = new Treeni(), treeni5 = new Treeni(), treeni6 = new Treeni(); 
    treenipaivakirja.lisaa(treeni3); assertEquals("From: Treenipaivakirja line: 130", 3, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni4); assertEquals("From: Treenipaivakirja line: 131", 4, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni5); assertEquals("From: Treenipaivakirja line: 132", 5, treenipaivakirja.getLkm()); 
    treenipaivakirja.lisaa(treeni6); assertEquals("From: Treenipaivakirja line: 133", 6, treenipaivakirja.getLkm()); 
    assertEquals("From: Treenipaivakirja line: 134", false, treeni1 == treeni2); 
    assertEquals("From: Treenipaivakirja line: 135", false, treeni3 == treeni4); 
    assertEquals("From: Treenipaivakirja line: 136", false, treeni1 == treeni6); 
  } // Generated by ComTest END
}